version: '3.8'

services:
  hello-world-app:
    image: nginx:alpine
    container_name: hello-world-container
    ports:
      - "80:80"
    volumes:
      - /home/www/app:/usr/share/nginx/html:ro
    restart: unless-stopped
