# DIGITAL OCEAN DROPLET SETTINGS
GITHUB_REPOSITORY: jasenmichael/droplet-app-template
GITHUB_REPOSITORY_BRANCH: main
DROPLET_NAME: your-droplet-name
DROPLET_SIZE: s-1vcpu-1gb
DROPLET_IMAGE: ubuntu-20-04-x64
DROPLET_REGION: nyc1
DROPLET_SSH_KEYS: "44084429"

# APPLICATION SETTINGS
APP_USER: www
APP_PATH: /home/www/app
PLAYBOOK_URL: "https://raw.githubusercontent.com/jasenmichael/ansible-droplet-playbooks/refs/heads/main/docker-compose-droplet-playbook.yml"
PLAYBOOK_PATH: "/home/www/docker-compose-droplet-playbook.yml"

# DOCKER SETTINGS
DOCKER_COMPOSE_PATH: "{{ APP_PATH }}/docker-compose.yml"
