GITHUB_REPOSITORY: "your-repo-name"
DROPLET_NAME: your-droplet-name
APP_PATH: "/home/www/app"
PLAYBOOK_URL: "https://raw.githubusercontent.com/jasenmichael/ansible-droplet-playbooks/refs/heads/main/docker-droplet-playbook.yml"
PLAYBOOK_PATH: "/home/www/docker-droplet-playbook.yml"
